heavymetalmachine/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("admin/", admin.site.urls),
]

posts/urls.py
from django.urls import path

from posts import views

app_name = "posts"
urlpatterns = [
    path("", views.PostIndexView.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update"),
]

posts/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=15)
    body_content = models.CharField(max_length=500)
    publish_date = models.DateTimeField("date published")

    def __repr__(self):
        return f"Post(title={self.title!r}, body_content={self.body_content!r}, publish_date={self.publish_date!r}"

    def __str__(self):
        return self.title

    def was_published_recently(self) -> bool:
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publish_date <= now

    def get_absolute_url(self) -> str:
        return reverse("posts:detail", kwargs={"pk": self.pk})

posts/views.py
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from posts.models import Post


class PostIndexView(ListView):
    context_object_name = "latest_posts_list"

    def get_queryset(self) -> QuerySet[Post]:
        """
        Return the last five published post (not including those set to be
        published in the future).
        """
        return Post.objects.filter(publish_date__lte=timezone.now()).order_by(
            "-publish_date"
        )[:5]


class PostDetailView(DetailView):
    model = Post

    def get_queryset(self) -> QuerySet[Post]:
        """
        Excludes any posts that aren't published yet.
        """
        return Post.objects.filter(publish_date__lte=timezone.now())


class PostCreateView(CreateView):
    model = Post
    fields = ["title", "body_content", "publish_date"]


class PostUpdateView(UpdateView):
    model = Post
    fields = ["title", "body_content", "publish_date"]


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("posts:index")

posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              <form action="{% url 'posts:update' post.id %}" method="post">
                {% csrf_token %}
                <div class="field">
                  <label class="label" for="title">Title</label>
                  <div class="control">
                    <input class="input" type="text" name="title" id="title" value="{{ post.title }}" required>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="body">Body</label>
                  <div class="control">
                    <textarea class="textarea" name="body" id="body">{{ post.body_content }}</textarea>
                  </div>
                </div>
                <div class="field">
                  <p class="control">
                    <input class="button is-success" type="submit" value="Save">
                  </p>
                </div>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>

posts/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
    <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              {% for post in latest_posts_list %}

                <div class="card">
                  <div class="card-content">
                    <p class="title has-text-centered">{{ post.title }}</p>
                    <p class="subtitle has-text-centered">on {{ post.publish_date }}</p>
                    <hr>
                    <div class="content">{{ post.body_content }}</div>
                  </div>
                </div>

              {% endfor %}
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>

posts/templates/posts/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              <form action="{% url 'posts:create' %}" method="post">
                {% csrf_token %}
                <div class="field">
                  <label class="label" for="title">Title</label>
                  <div class="control">
                    <input class="input" type="text" name="title" id="title" value="{{ post.title }}" required>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="body">Body</label>
                  <div class="control">
                    <textarea class="textarea" name="body" id="body">{{ post.body_content }}</textarea>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="publish_date">Publish Date</label>
                  <div class="control">
                    <input class="input" type="datetime-local" name="publish_date" id="publish_date" value="{{ post.publish_date|date:'Y-m-d' }}T{{ post.publish_date|time:'H:i:s' }}" required>
                  </div>
                </div>
                <div class="field">
                  <p class="control">
                    <input class="button is-success" type="submit" value="Save">
                  </p>
                </div>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>

posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              <form action="{% url 'posts:update' post.id %}" method="post">
                {% csrf_token %}
                <div class="field">
                  <label class="label" for="title">Title</label>
                  <div class="control">
                    <input class="input" type="text" name="title" id="title" value="{{ post.title }}" required>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="body">Body</label>
                  <div class="control">
                    <textarea class="textarea" name="body" id="body">{{ post.body_content }}</textarea>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="publish_date">Publish Date</label>
                  <div class="control">
                    <input class="input" type="datetime-local" name="publish_date" id="publish_date" value="{{ post.publish_date|date:'Y-m-d' }}T{{ post.publish_date|time:'H:i:s' }}" required>
                  </div>
                </div>
                <div class="field">
                  <p class="control">
                    <input class="button is-success" type="submit" value="Save">
                  </p>
                </div>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>

posts/templates/posts/post_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              {% if post.id is not None %}
                <form action="{% url 'posts:update' post.id %}" method="post">
              {% else %}
                <form action="{% url 'posts:create' %}" method="post">
              {% endif %}
                {% csrf_token %}
                <div class="field">
                  <label class="label" for="title">Title</label>
                  <div class="control">
                    <input class="input" type="text" name="title" id="title" value="{{ post.title }}" required>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="body_content">Body</label>
                  <div class="control">
                    <textarea class="textarea" name="body_content" id="body_content">{{ post.body_content }}</textarea>
                  </div>
                </div>
                <div class="field">
                  <label class="label" for="publish_date">Publish Date</label>
                  <div class="control">
                    <input class="input" type="datetime-local" name="publish_date" id="publish_date" value="{{ post.publish_date|date:'Y-m-d' }}T{{ post.publish_date|time:'H:i:s' }}" required>
                  </div>
                </div>
                <div class="field">
                  <p class="control">
                    <input class="button is-success" type="submit" value="Save">
                  </p>
                </div>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>

posts/templates/posts/post_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
    <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              {% for post in latest_posts_list %}

                <div class="card">
                  <div class="card-content">
                    <p class="title has-text-centered">{{ post.title }}</p>
                    <p class="subtitle has-text-centered">on {{ post.publish_date }}</p>
                    <hr>
                    <div class="content">{{ post.body_content }}</div>
                  </div>
                </div>

              {% endfor %}
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>